export default function Success() {
  const token = localStorage.getItem("token")
  const user = JSON.parse(localStorage.getItem("user") || "{}")

  if (!token) return <h1>you are not signed in</h1>

  return (
    <div>
      <h1>success, you are signed in with google!</h1>

      <h2>From Google</h2>
      <p>Name: {user.displayName}</p>
      <p>Email: {user.email}</p>

      <h2>Generated by us</h2>
      <p>Handle: {user.handle}</p>
      <p>Role: {user.role}</p>
      <p>Member since: {user.createdAt}</p>
    </div>
  )
}
